name: Beta Deploy

on:
  push:
    branches: [ dev ]

jobs:
  beta-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        uses: Borales/actions-yarn@v3
        with:
          cmd: install

      - name: Build for production
        uses: Borales/actions-yarn@v3
        with:
          cmd: export

      - name: Deploy to GithubPage
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
