name: Beta Deploy

on:
  push:
    branches: [ dev ]

jobs:
  beta-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: data-map
        id: data-map
        run: |
          echo '::set-output name=DATA_MAP::{"refs/heads/dev":"decoo-cn-home-deploy"}'

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build for production
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: export

      - name: Deploy to decooio/decoo-cn-home-deploy
        uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.DECOO_PAT }}
          SRC_FOLDER: out
          DEST_OWNER: decooio
          DEST_REPO: ${{ fromJSON(steps.data-map.outputs.DATA_MAP)[github.ref] }}
          DEST_BRANCH: main
          DEST_FOLDER: docs
