# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Prod Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main, baitech ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DECOO_PAT }}

      - name: Login to private docker registry
        uses: docker/login-action@v1
        with:
          registry: decoo-registry.tencentcloudcr.com
          username: ${{ secrets.TCR_USER }}
          password: ${{ secrets.TCR_PASSWD}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/decooio/bacoo-home:latest, decoo-registry.tencentcloudcr.com/decooio/bacoo-home:latest
